---

- name: Activate ES license (without security authentication)
  uri:
    method: PUT
    url: "http://{{es_api_host}}:{{es_api_port}}/_xpack/license?acknowledge=true"
    body_format: json
    body: "{{ es_xpack_license }}"
    return_content: yes
  register: license_activated
  no_log: False
  when: 'not "security" in es_xpack_features'
  ignore_errors: yes

- name: Activate ES license (with security authentication)
  uri:
    method: PUT
    url: "http://{{es_api_host}}:{{es_api_port}}/_xpack/license?acknowledge=true"
    user: "{{es_api_basic_auth_username}}"
    password: "{{es_api_basic_auth_password}}"
    body_format: json
    force_basic_auth: yes
    body: "{{ es_xpack_license }}"
    return_content: yes
  register: license_activated
  no_log: False
  when: '"security" in es_xpack_features'
  ignore_errors: yes

- debug:
    msg: "License: {{ license_activated }}"
